# Generated by Django 5.1.2 on 2024-10-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_url_expiration_time_url_max_usage_url_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
