# Generated by Django 5.1.2 on 2024-10-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_url_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='used_times',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
