# Generated by Django 5.1.2 on 2024-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_url_used_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='url',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
    ]
