# Generated by Django 5.1.2 on 2024-10-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_approvalrequest_owner_alter_approvalrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='approved',
            field=models.BooleanField(blank=True, help_text='False means rejected!', null=True),
        ),
    ]
