# Generated by Django 5.1.2 on 2024-10-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_alter_approvalrequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
